Repository codesquad-member-2020/issue-tracker-12, pull requests merged in 2020-06, with the labels that each got.

#2 [FE #1] Vue 프로젝트 생성
  FE/vue/README.md
  FE/vue/babel.config.js
  FE/vue/package-lock.json
  FE/vue/package.json
  FE/vue/public/favicon.ico
  FE/vue/public/index.html
  FE/vue/src/App.vue
  FE/vue/src/assets/logo.png
  FE/vue/src/main.js
Labels: Vue

#8 [#4] chore : 기본 개발환경 설정
  BE/issue-tracker/.gitignore
  BE/issue-tracker/build.gradle
  BE/issue-tracker/gradle/wrapper/gradle-wrapper.jar
  BE/issue-tracker/gradle/wrapper/gradle-wrapper.properties
  BE/issue-tracker/gradlew
  BE/issue-tracker/gradlew.bat
  BE/issue-tracker/settings.gradle
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/IssueTrackerApplication.java
  BE/issue-tracker/src/main/resources/application-deploy.properties
  BE/issue-tracker/src/main/resources/application-dev.properties
  BE/issue-tracker/src/main/resources/application.properties
  BE/issue-tracker/src/test/java/dev/codesquad/issuetracker/IssueTrackerApplicationTests.java
Labels: BE

#11 [BE] OAuth 기능 구현 완료
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/cors/SimpleCorsFilter.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/cors/WebConfig.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/exception/ExceptionAdvice.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/exception/InvalidTokenException.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/jwt/JwtService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/Github.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/GithubUser.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/LoginService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/RequestBody.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/controller/LoginController.java
  BE/issue-tracker/src/main/resources/application-dev.properties
Labels: BE

#13 [FE #2] React 환경 설정
  FE/react/.env.development
  FE/react/.env.production
  FE/react/.gitignore
  FE/react/.prettierrc
  FE/react/.storybook/main.js
  FE/react/babel.config.js
  FE/react/fileTransformer.js
  FE/react/jest.config.js
  FE/react/package-lock.json
  FE/react/package.json
  FE/react/public/index.html
  FE/react/src/App.tsx
  FE/react/src/index.tsx
  FE/react/src/typings.d.ts
  FE/react/tsconfig.json
  FE/react/webpack.config.js
  FE/react/webpack.dev.js
  FE/react/webpack.prod.js
Labels: React

#23 Feature fe/issue 15
  FE/react/.gitignore
  FE/react/.storybook/main.js
  FE/react/now.json
  FE/react/package-lock.json
  FE/react/package.json
  FE/react/src/Custom/Button/Button.tsx
  FE/react/src/Custom/CommentBox/CommentBox.tsx
  FE/react/src/Custom/FilterButton/FilterButton.tsx
  FE/react/src/Custom/Flex/Flex.tsx
  FE/react/src/Custom/Label/Label.tsx
  FE/react/src/Custom/OptionButton/OptionButton.tsx
  FE/react/src/Custom/Row/Row.tsx
  FE/react/src/Custom/Tab/Tab.tsx
  FE/react/src/Icon/Icon.tsx
  FE/react/src/Icon/svg/arrow.svg
  FE/react/src/Icon/svg/check.svg
  FE/react/src/Icon/svg/close.svg
  FE/react/src/Icon/svg/exclamation.svg
  FE/react/src/Icon/svg/github.svg
  FE/react/src/Icon/svg/index.ts
  FE/react/src/Icon/svg/option.svg
  FE/react/src/Icon/svg/tog.svg
  FE/react/src/stories/Button.stories.tsx
  FE/react/src/stories/CommentBox.stories.tsx
  FE/react/src/stories/FilterButton.stories.tsx
  FE/react/src/stories/Flex.stories.tsx
  FE/react/src/stories/OptionButton.stories.tsx
  FE/react/src/stories/Tab.stories.tsx
  FE/react/src/util/customHooks/useFocusOut.tsx
  FE/react/tsconfig.json
  FE/react/webpack.dev.js
  FE/react/webpack.prod.js
Labels: React

#29 [BE] 이슈 목록 기능 추가
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/IssueRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/IssueController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/IssueResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/LabelDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/MilestoneDto.java
Labels: BE

#32 메인 화면 작성
  FE/react/.storybook/main.js
  FE/react/src/App.tsx
  FE/react/src/Components/Header/Header.tsx
  FE/react/src/Components/Main/Body/Body.tsx
  FE/react/src/Components/Main/Body/Row/Row.tsx
  FE/react/src/Components/Main/Header/Header.tsx
  FE/react/src/Custom/Button/Button.tsx
  FE/react/src/Custom/FilterButton/FilterButton.tsx
  FE/react/src/Custom/Flex/Flex.tsx
  FE/react/src/Custom/Input/Input.tsx
  FE/react/src/Custom/Label/Label.tsx
  FE/react/src/Custom/LabelButton/LabelButton.tsx
  FE/react/src/Custom/OptionButton/OptionButton.tsx
  FE/react/src/Icon/Icon.tsx
  FE/react/src/Icon/svg/index.ts
  FE/react/src/Icon/svg/magnifier.svg
  FE/react/src/Icon/svg/tag.svg
  FE/react/src/Icon/svg/task.svg
  FE/react/src/Icon/svg/tog.svg
  FE/react/src/Page/Issue/Issue.tsx
  FE/react/src/Page/Label/Label.tsx
  FE/react/src/Page/Main/Main.tsx
  FE/react/src/stories/Button.stories.tsx
  FE/react/src/stories/CommentBox.stories.tsx
  FE/react/src/stories/FilterButton.stories.tsx
  FE/react/src/stories/Flex.stories.tsx
  FE/react/src/stories/Header.stories.tsx
  FE/react/src/stories/Input.stories.tsx
  FE/react/src/stories/LabelButton.stories.tsx
  FE/react/src/stories/Tab.stories.tsx
  FE/react/tsconfig.json
  FE/react/webpack.dev.js
  FE/react/webpack.prod.js
Labels: FE, FE-Review

#36 [FE #33] 새로운 이슈 등록하는 화면 작성
  FE/react/src/App.tsx
  FE/react/src/Components/NewIssue/Input/Input.tsx
  FE/react/src/Components/NewIssue/OptionButtons/OptionButtons.tsx
  FE/react/src/Components/NewIssue/Text/Text.tsx
  FE/react/src/Custom/OptionButton/OptionButton.tsx
  FE/react/src/Custom/Tab/Tab.tsx
  FE/react/src/Page/NewIssue/NewIssue.tsx
Labels: FE, React

#37 [FE #21] 레이블 목록화면
  FE/vue/package-lock.json
  FE/vue/package.json
  FE/vue/public/github.css
  FE/vue/public/index.html
  FE/vue/src/App.vue
  FE/vue/src/assets/Labels.svg
  FE/vue/src/assets/labelChange.svg
  FE/vue/src/assets/milestone.svg
  FE/vue/src/components/common/CreateButton.vue
  FE/vue/src/components/common/RouterBox.vue
  FE/vue/src/components/common/RouterButton.vue
  FE/vue/src/components/issue/label/AddLabel.vue
  FE/vue/src/components/issue/label/ContentComponent.vue
  FE/vue/src/components/issue/label/EditLabel.vue
  FE/vue/src/components/issue/label/HeaderComponent.vue
  FE/vue/src/components/issue/label/Label.vue
  FE/vue/src/components/issue/label/LabelBox.vue
  FE/vue/src/components/issue/milestone/ContentComponent.vue
  FE/vue/src/components/issue/milestone/HeaderComponent.vue
  FE/vue/src/components/issueList/FilterComponent.vue
  FE/vue/src/components/issueList/LabelsButtonComponent.vue
  FE/vue/src/components/issueList/MileStoneButtonComponent.vue
  FE/vue/src/routes/index.js
  FE/vue/src/store/index.js
  FE/vue/src/style/globalStyle.js
  FE/vue/src/style/styled.js
  FE/vue/src/utils/utils.js
  FE/vue/src/views/IssueListPage.vue
  FE/vue/src/views/LabelListPage.vue
  FE/vue/src/views/MilestoneListPage.vue
Labels: Vue

#40 [BE] Label API 구현
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/exception/DataNotFoundException.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/exception/ExceptionAdvice.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/label/Label.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/LabelRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/LabelService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/LabelController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/LabelDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/IssueResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/label/LabelDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/label/LabelRequest.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/milestone/MilestoneDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/milestone/MilestoneResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/user/UserResponse.java
  BE/issue-tracker/src/main/resources/application-deploy.properties
  BE/issue-tracker/src/main/resources/application.properties
  BE/issue-tracker/src/main/resources/data.sql
  BE/issue-tracker/src/test/java/dev/codesquad/issuetracker/service/LabelServiceTest.java
Labels: BE

#41 [FE #39] MileStone 화면
  FE/vue/src/assets/calendar.svg
  FE/vue/src/assets/check.svg
  FE/vue/src/components/issue/label/HeaderComponent.vue
  FE/vue/src/components/issue/milestone/CloseMilestone.vue
  FE/vue/src/components/issue/milestone/ContentComponent.vue
  FE/vue/src/components/issue/milestone/HeaderComponent.vue
  FE/vue/src/components/issue/milestone/MileStoneList.vue
  FE/vue/src/components/issue/milestone/Milestone.vue
  FE/vue/src/components/issue/milestone/MilestoneBox.vue
  FE/vue/src/components/issue/milestone/OpenMilestone.vue
  FE/vue/src/components/issue/milestone/StateMilestoneButton.vue
  FE/vue/src/store/index.js
  FE/vue/src/style/styled.js
  FE/vue/src/views/MilestoneListPage.vue
Labels: Vue

#43 [FE #42] Axios Interseptor
  FE/vue/src/api/common/interceptors.js
  FE/vue/src/api/index.js
  FE/vue/src/api/issue.js
Labels: Vue

#22 Feature fe/issue 15
  FE/react/.gitignore
  FE/react/.storybook/main.js
  FE/react/now.json
  FE/react/package-lock.json
  FE/react/package.json
  FE/react/src/Custom/Button/Button.tsx
  FE/react/src/Custom/CommentBox/CommentBox.tsx
  FE/react/src/Custom/FilterButton/FilterButton.tsx
  FE/react/src/Custom/Flex/Flex.tsx
  FE/react/src/Custom/Label/Label.tsx
  FE/react/src/Custom/OptionButton/OptionButton.tsx
  FE/react/src/Custom/Row/Row.tsx
  FE/react/src/Custom/Tab/Tab.tsx
  FE/react/src/Icon/Icon.tsx
  FE/react/src/Icon/svg/arrow.svg
  FE/react/src/Icon/svg/check.svg
  FE/react/src/Icon/svg/close.svg
  FE/react/src/Icon/svg/exclamation.svg
  FE/react/src/Icon/svg/github.svg
  FE/react/src/Icon/svg/index.ts
  FE/react/src/Icon/svg/option.svg
  FE/react/src/Icon/svg/tog.svg
  FE/react/src/stories/Button.stories.tsx
  FE/react/src/stories/CommentBox.stories.tsx
  FE/react/src/stories/FilterButton.stories.tsx
  FE/react/src/stories/Flex.stories.tsx
  FE/react/src/stories/OptionButton.stories.tsx
  FE/react/src/stories/Tab.stories.tsx
  FE/react/src/util/customHooks/useFocusOut.tsx
  FE/react/tsconfig.json
  FE/react/webpack.dev.js
  FE/react/webpack.prod.js
Labels: FE-Review

#47 이슈 상세 화면 페이지 작성
  FE/react/src/App.tsx
  FE/react/src/Components/Detail/Detail.tsx
  FE/react/src/Custom/Button/Button.tsx
  FE/react/src/Custom/CommentBox/CommentBox.tsx
  FE/react/src/Custom/CommentBoxWithImg/CommentBoxWithImg.tsx
  FE/react/src/Page/Detail/Detail.tsx
  FE/react/src/stories/CommentBoxWithImg.stories.tsx
Labels: FE

#49 [BE] 이슈 생성 API 구현
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/issue/Issue.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/user/User.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/LabelRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/UserRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/MilestoneService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/UserService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/IssueController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/MilestoneController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/UserController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/IssueCreateResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/IssueRequest.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/milestone/MilestoneDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/user/UserResponse.java
Labels: BE

#50 [FE #48] 버튼 클릭 시 화면 이동 구현
  FE/react/public/index.html
  FE/react/src/Components/Main/Header/Header.tsx
Labels: FE, React

#52 [BE] 마일스톤 응답 타입 변경
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/IssueResponse.java
Labels: BE

#54 [FE #44] Milestone Component
  FE/vue/src/components/common/CancelButton.vue
  FE/vue/src/components/issue/label/EditLabel.vue
  FE/vue/src/components/issue/milestone/CloseMilestone.vue
  FE/vue/src/components/issue/milestone/HeaderComponent.vue
  FE/vue/src/components/issue/milestone/MileStoneList.vue
  FE/vue/src/components/issue/milestone/Milestone.vue
  FE/vue/src/components/issue/milestone/OpenMilestone.vue
  FE/vue/src/components/issue/milestone/StateMilestoneButton.vue
  FE/vue/src/components/issue/milestone/create/CreateMilestone.vue
  FE/vue/src/components/issue/milestone/create/CreateMilestoneContent.vue
  FE/vue/src/components/issue/milestone/create/CreateMilestoneHeader.vue
  FE/vue/src/routes/index.js
  FE/vue/src/store/index.js
  FE/vue/src/style/styled.js
  FE/vue/src/views/CreateMilestonePage.vue
Labels: Vue

#58 [FE #55] issue List filter button 구현
  FE/vue/package-lock.json
  FE/vue/package.json
  FE/vue/public/index.html
  FE/vue/src/assets/issue.svg
  FE/vue/src/assets/search.svg
  FE/vue/src/components/issue/issue/ContentComponent.vue
  FE/vue/src/components/issue/issue/FilterItem.vue
  FE/vue/src/components/issue/issue/HeaderComponent.vue
  FE/vue/src/components/issue/issue/HeaderFilter.vue
  FE/vue/src/components/issue/issue/IssueBox.vue
  FE/vue/src/components/issue/issue/StateIssueButton.vue
  FE/vue/src/main.js
  FE/vue/src/store/index.js
  FE/vue/src/style/globalStyle.js
  FE/vue/src/style/styled.js
  FE/vue/src/views/IssueListPage.vue
Labels: Vue

#30 [BE 리뷰요청] 백엔드 1주차 리뷰요청
  .github/ISSUE_TEMPLATE/-be--henry-title.md
  .github/ISSUE_TEMPLATE/-fe--huey-title.md
  .github/ISSUE_TEMPLATE/-fe--won-title.md
  BE/issue-tracker/.gitignore
  BE/issue-tracker/build.gradle
  BE/issue-tracker/gradle/wrapper/gradle-wrapper.jar
  BE/issue-tracker/gradle/wrapper/gradle-wrapper.properties
  BE/issue-tracker/gradlew
  BE/issue-tracker/gradlew.bat
  BE/issue-tracker/settings.gradle
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/IssueTrackerApplication.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/cors/SimpleCorsFilter.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/cors/WebConfig.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/exception/ExceptionAdvice.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/exception/InvalidTokenException.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/jwt/JwtService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/Github.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/GithubUser.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/LoginService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/common/oauth/RequestBody.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/Status.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/issue/Comment.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/issue/Issue.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/label/Label.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/user/User.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/IssueRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/LabelRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/UserRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/IssueController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/LoginController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/IssueResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/LabelDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/MilestoneDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/MilestoneResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/ResultDto.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/ResultResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/UserResponse.java
  BE/issue-tracker/src/main/resources/application-deploy.properties
  BE/issue-tracker/src/main/resources/application-dev.properties
  BE/issue-tracker/src/main/resources/application.properties
  BE/issue-tracker/src/main/resources/data.sql
  BE/issue-tracker/src/test/java/dev/codesquad/issuetracker/IssueTrackerApplicationTests.java
  FE/vue/README.md
  FE/vue/babel.config.js
  FE/vue/package-lock.json
  FE/vue/package.json
  FE/vue/public/favicon.ico
  FE/vue/public/index.html
  FE/vue/src/App.vue
  FE/vue/src/assets/logo.png
  FE/vue/src/main.js
  README.md
Labels: BE, BE-리뷰요청

#61 [FE #55] DetailIssue 페이지 스타일 구현
  FE/vue/src/assets/comment.svg
  FE/vue/src/assets/issueIcon.svg
  FE/vue/src/assets/issueMilestone.svg
  FE/vue/src/components/issue/issue/ContentComponent.vue
  FE/vue/src/components/issue/issue/FilterItem.vue
  FE/vue/src/components/issue/issue/IssueBox.vue
  FE/vue/src/components/issue/issue/IssueDetail.vue
  FE/vue/src/components/issue/issue/IssueItem.vue
  FE/vue/src/components/issue/issue/IssueList.vue
  FE/vue/src/store/index.js
  FE/vue/src/style/styled.js
  FE/vue/src/views/CreateIssuePage.vue
Labels: Vue

#62 [BE] 이슈 필터링 API
  BE/issue-tracker/build.gradle
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/IssueQueryRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/IssueRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/IssueController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/LabelController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/FilterParam.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/StatusRequest.java
Labels: BE

#64 [BE] 이슈 조회 쿼리 최적화
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/IssueRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/resources/application-dev.properties
Labels: BE

#66 [BE] 마일스톤 목록 API
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/issue/Issue.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/domain/milestone/Milestone.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/IssueRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/repository/MilestoneRepository.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/IssueService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/service/MilestoneService.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/IssueController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/controller/MilestoneController.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/ResultDtoResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/ResultResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/milestone/MilestoneRequest.java
Labels: BE

#68 [BE] 마일스톤 목록 수정 API
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/IssueStatusResponse.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/milestone/MilestoneDto.java
  BE/issue-tracker/src/main/resources/application.properties
Labels: BE

#70 [BE] 단위 테스트 작성
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/FilterParam.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/issue/IssueRequest.java
  BE/issue-tracker/src/main/java/dev/codesquad/issuetracker/web/dto/label/LabelRequest.java
  BE/issue-tracker/src/test/java/dev/codesquad/issuetracker/service/IssueServiceTest.java
  BE/issue-tracker/src/test/java/dev/codesquad/issuetracker/service/LabelServiceTest.java
Labels: BE
